# Generated by Django 2.2.8 on 2019-12-11 19:17

import aphdstreaming.livestream.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('Bride', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(code='invalid_name', message='name should contain only alphabets', regex='^[a-zA-Z\\s]*$')])),
                ('Groom', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(code='invalid_name', message='name should contain only alphabets', regex='^[a-zA-Z\\s]*$')])),
                ('Message', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(code='invalid_name', message='message should contain only alphabets', regex='^[a-zA-Z\\s]*$')])),
                ('time', models.DateTimeField(verbose_name='Event Time')),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('CONFIRMED', 'Confirmed'), ('INPROGRESS', 'Inprogress'), ('COMPLETED', 'Completed')], default='CREATED', max_length=15)),
                ('Bride_Img', models.ImageField(blank=True, null=True, upload_to=aphdstreaming.livestream.models.stream_directory_path)),
                ('Groom_Img', models.ImageField(blank=True, null=True, upload_to=aphdstreaming.livestream.models.stream_directory_path)),
                ('Poster_Img', models.ImageField(blank=True, null=True, upload_to=aphdstreaming.livestream.models.stream_directory_path)),
                ('Studio', models.CharField(max_length=80)),
                ('Stream_Key', models.CharField(editable=False, max_length=80)),
                ('start_date_time', models.DateTimeField(verbose_name='Start Date Time')),
                ('end_date_time', models.DateTimeField(verbose_name='End Date Time')),
                ('studio_person', models.CharField(blank=True, max_length=80, null=True)),
                ('studio_phone', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(code='invalid Phone number', message='Phone number should contain only 10 numbers', regex='^[0-9]{10}$')])),
                ('studio_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=aphdstreaming.livestream.models.images_stream_directory_path)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='livestream.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
